# Generated by Django 4.2 on 2023-10-22 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="semester",
            field=models.CharField(
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        message="請輸入正確的學期", regex="\\d{3}\\-[1-2]"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="請輸入正確的email",
                        regex="\\w[\\w\\.-]*@\\w[\\w\\.-]+\\.\\w+",
                    )
                ],
            ),
        ),
    ]
