# Generated by Django 4.2 on 2023-10-22 16:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_grade_semester_alter_student_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["-id"],
                "verbose_name": "學生",
                "verbose_name_plural": "學生",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"verbose_name": "科目", "verbose_name_plural": "科目"},
        ),
    ]
