# Generated by Django 4.2 on 2023-10-22 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_student_options_alter_subject_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="phoneNumber",
            field=models.IntegerField(
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="請輸入正確的手機號碼", regex="^\\+?1?\\d{8,15}$"
                    )
                ],
                verbose_name="手機",
            ),
        ),
    ]
