# Generated by Django 4.2 on 2023-10-26 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_student_phonenumber"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={"verbose_name": "成績", "verbose_name_plural": "成績"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={
                "ordering": ["id"],
                "verbose_name": "學生",
                "verbose_name_plural": "學生",
            },
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("student", "semester", "subject")},
        ),
    ]
