# Generated by Django 4.2 on 2023-11-12 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_grade_options_alter_student_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="phoneNumber",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="請輸入正確的手機號碼", regex="^\\+?1?\\d{8,15}$"
                    )
                ],
                verbose_name="手機",
            ),
        ),
    ]
