# Generated by Django 4.2 on 2023-11-12 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_student_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.student",
                verbose_name="學生",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="subject",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.subject",
                verbose_name="科目",
            ),
        ),
    ]
