# Generated by Django 4.2 on 2023-11-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_grade_student_alter_grade_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.IntegerField(
                choices=[(0, "男"), (1, "女"), (2, "未知")], default=2, verbose_name="性別"
            ),
        ),
    ]
