# Generated by Django 3.2.22 on 2023-11-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_student_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'permissions': (('readGrade', 'readGrade'), ('createGrade', 'createGrade'), ('updateGrade', 'updateGrade'), ('deleteGrade', 'deleteGrade')), 'verbose_name': '成績', 'verbose_name_plural': '成績'},
        ),
    ]
